export const constantsDark = {
  text_size: {
    s1: "tw-text-sm",
    s2: "tw-text-base",
    s3: "tw-text-lg",
    s4: "tw-text-xl",
    s5: "tw-text-2xl",
    s6: "tw-text-4xl",
  },
  primary: "#07e47d",
  primary_light: "#006033",
  secondary: "#ccc",
  secondary_light: "#D9D9D9",
  danger: "#FF4C00",
  warning: "#F4A100",
  success: "#32B573",
  light: "#333",
  dark: "#fff",
  layout_background: "#555",
  input_background: "#555",
  transparent_level: "15",
  mode: "DARK",
};
