export const constants = {
    text_size: {
        s1: 'tw-text-sm',
        s2: 'tw-text-md',
        s3: 'tw-text-lg',
        s4: 'tw-text-xl',
        s5: 'tw-text-2xl',
        s6: 'tw-text-4xl',
    },
    primary: "#006033",
    primary_light: "#006033",
    secondary: "#3D434A",
    danger: '#F40',
    warning: '#F4A100',
    light:'#F5F6FA',
    transparent_level:50,

    g1: '#CCDFD6',
    g2: '#80AF99',
    g3: '#559577',
    g4: '#006033',
    g5: '#004022',
    g6: '#002011',
}
 /*  text_size: {
    xs1: "tw-text-[9px]",
    s1: "tw-text-sm",
    s2: "tw-text-md",
    s3: "tw-text-lg",
    s4: "tw-text-xl",
    s5: "tw-text-2xl",
    s6: "tw-text-4xl",
  },

  color: {
    primary: "tw-text-[#006033]",
    primary_light: "tw-text-[#D1EFDF]",
    primary_lighter: "tw-text-[#CCDFD6]",
    danger: "tw-text-[#FF4C00]",
    danger_light: "tw-text-[#FFD6C5]",
    secondary: "tw-text-[#3D434A]",
    secondary_light: "tw-text-[#7A7B78]",
    warning: "tw-text-[#92400E]",
    warning_light: "tw-text-[#FEF3C7]",
    light: "tw-text-[#F5F6FA]",
    dark: "tw-text-[#3D434A]",
  },

  bg: {
    primary: "tw-bg-[#006033]",
    primary_light: "tw-bg-[#D1EFDF]",
    primary_lighter: "tw-bg-[#CCDFD6]",
    danger: "tw-bg-[#FF4C00]",
    danger_light: "tw-bg-[#FFD6C5]",
    secondary: "tw-bg-[#3D434A]",
    secondary_light: "tw-bg-[#7A7B78]",
    warning: "tw-bg-[#92400E]",
    warning_light: "tw-bg-[#FEF3C7]",
    light: "tw-bg-[#F5F6FA]",
    dark: "tw-bg-[#3D434A]",
  },
};
   */
